services:
  - type: web
    name: attendance-system
    env: python
    runtime: python-3.9
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-system-db
      - key: SECRET_KEY
        sync: false  
